name: test
workspace:
  base: /test

cluster:
  action: EnsureCluster
  secret:
    name: eks-admin
  name: eks-cicd-cluster-1
  cloud: amazon
  location: eu-central-1


pipeline:
  
  dep_redis:
    parallel: true
    image: banzaicloud/ci-pipeline-client:latest
    action: CreateDeployment
    deployment:
      name: stable/redis
      releaseName: t-gamma-cache
      namespace: test
      values:
        redisPort: 6379
        password: just_another_password
        image:
          fullnameOverride: t-gamma-cache

  dep_postgres:
    image: banzaicloud/ci-pipeline-client:latest
    action: CreateDeployment 
    deployment:
      name: stable/postgresql
      releaseName: t-gamma-db
      namespace: test
      values:
        postgresqlUsername: postgres
        postgresqlPassword: just_another_password
        postgresqlDatabase: gamma
        image:
          fullnameOverride: t-gamma-db

  test:
    image: python:3.6
    environment:
      - SECRET_KEY=just_another_secret_key
      - FLASK_ENV=development
      - TESTING=True
      - FLASK_DEBUG=True
    commands:
      - pip install --no-cache -r requirements.txt
      - make tests

  del_redis:
    image: banzaicloud/ci-pipeline-client:latest
    action: DeleteDeployment
    deployment:
      releaseName: t-gamma-cache
      namespace: test

  del_postgres:
    image: banzaicloud/ci-pipeline-client:latest
    action: DeleteDeployment 
    deployment:
      releaseName: t-gamma-db
      namespace: test

trigger:
  events:
    - [ pull_request ]
      
---
workspace:
  base: /backend
name: deploy

cluster:
  action: EnsureCluster
  secret:
    name: eks-admin
  name: eks-cicd-cluster-1
  cloud: amazon
  location: eu-central-1

pipeline:
    redis:
      image: banzaicloud/ci-pipeline-client:latest
      action: EnsureDeployment
      deployment:
        name: stable/redis
        releaseName: p-gamma-cache
        namespace: prod
        values:
          redisPort: 6379
          password: just_another_password
          image:
            fullnameOverride: p-gamma-cache
  
    postgres:
      image: banzaicloud/ci-pipeline-client:latest
      action: EnsureDeployment 
      deployment:
        name: stable/postgresql
        releaseName: p-gamma-db
        namespace: prod
        values:
          postgresqlUsername: postgres
          postgresqlPassword: just_another_password
          postgresqlDatabase: gamma
          image:
            fullnameOverride: p-gamma-db

    
trigger:
  branches:
    - master
  events:
    - [ tag, deployment ]